### PR TITLE
Fix STM32F4 erase time

### LINKED ISSUE #81: Flashing issues on uwb board
The UWB board has some issues with flashing. It might be due to the microcontroller having larger pages, causing timeouts.

Example output:

```
Flashing firmware (size: 232244 bytes)
Erasing pages...
Traceback (most recent call last):
  File "/usr/local/bin/bootloader_flash", line 11, in <module>
    load_entry_point('cvra-bootloader==2.1.0', 'console_scripts', 'bootloader_flash')()
  File "/usr/local/lib/python3.6/site-packages/cvra_bootloader/bootloader_flash.py", line 200, in main
    args.ids, page_size=args.page_size)
  File "/usr/local/lib/python3.6/site-packages/cvra_bootloader/bootloader_flash.py", line 75, in flash_binary
    pbar.update(offset)
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 579, in update
    StdRedirectMixin.update(self, value=value)
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 141, in update
    DefaultFdMixin.update(self, value=value)
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 68, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 508, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 483, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "/usr/local/lib/python3.6/site-packages/progressbar/widgets.py", line 405, in __call__
    return ETA.__call__(self, progress, data, value=value, elapsed=elapsed)
  File "/usr/local/lib/python3.6/site-packages/progressbar/widgets.py", line 339, in __call__
    progress, data, value=value, elapsed=elapsed)
  File "/usr/local/lib/python3.6/site-packages/progressbar/widgets.py", line 321, in _calculate_eta
    eta_seconds = remaining * per_item
OverflowError: days=1209096132; must have magnitude <= 999999999
100% (232244 of 232244) |#######################################################| Elapsed Time: 0:00:00 Time: 0:00:00
```

### PR DESCRIPTION
**Pull request by antoinealb**
This pull request enables flashing of STM32F4 based boards in a reasonable time. It does so by avoiding erasing several time the same "big" sector which is expensive to do on this platform. See commits for implementation details.

The alternative would have been to make the client aware of the more complex sector layout to avoid erasing unnecessary sectors. However this meant either more client-side configuration (commandline flags) to indicate that this is an STM32F4 or a discovery step (for example by reading the board config). In the end I feel that "hacking" the interface leads to a simpler system.

Flashing time with this path is about 30s for the UWB firmware, which is reasonable enough to allow in system flashing of the board.

As a bonus I added a blink pattern to identify the boards which boot in bootloader mode.

Fixes #81

### CODE REVIEW

**Review by Lu-ni — COMMENTED** [review]
f58850f :
In the datasheet of STM32F4 i find the following

| 0xA000 0000 - 0xA000 0FFF FSMC | control register | 
|-|-|
0x9000 0000 - 0x9FFF FFFF FSMC | bank 4
0x8000 0000 - 0x8FFF FFFF FSMC | bank 3
0x7000 0000 - 0x7FFF FFFF FSMC | bank 2
0x6000 0000 - 0x6FFF FFFF FSMC | bank 1

Do we start at 0x8000 0000 because 0x6000 0000 and 0x7000 0000 are for the bootloader ?

The arg -d take "0483:df11", i can't find it on the datasheet of MC, where does it come from ?

**Comment by antoinealb** [comment]
> Do we start at 0x8000 0000 because 0x6000 0000 and 0x7000 0000 are for the bootloader ?

I think you mixed up 0x**80**00 0000 and 0x**08**00 0000. The table you shown here is from the register space (the device peripherals basically), whereas we are interested in memory. See below for details. We put the bootloader at the start of the memory, then two sectors of config, then the application. You can find our memory layout in the [linker script](https://github.com/cvra/can-bootloader/blob/master/platform/uwb-beacon/linkerscript.ld#L7-L10). The TEXT section means "the program", here it is the bootloader.
 
> The arg -d take "0483:df11", i can't find it on the datasheet of MC, where does it come from ?

This is the Vendor ID and Product ID of an STM32 in bootloader mode. Each device manufactured has such IDs and they must be unique. You can find them by running `lsusb` under Linux.

File: platform/uwb-beacon/platform.c [hunk 1]
```diff
@@ -64,6 +65,27 @@ void fault_handler(void)
...
+static void delay(int n)
+{
+    for (volatile int i = 0; i < n; i++) {
+        asm volatile ("nop");
+    }
+}
+
+static void reboot_blink(void)
+{
+    const int period = 700 * 1000;
```
Comment (Lu-ni) [inline platform/uwb-beacon/platform.c:78]: How did you get 700 ?

File: platform/mcu/stm32f4/flash_writer.c [hunk 2]
```diff
@@ -8,6 +8,10 @@
 #define FLASH_PROGRAM_SIZE 0 // default: 8-bit
 #endif
 
+#define SECTOR_COUNT 24
```
Comment (Lu-ni) [inline platform/mcu/stm32f4/flash_writer.c:11]: How do you get the sector_count value ?

**Review by Lu-ni — APPROVED** [review]
LGTM !

File: platform/uwb-beacon/platform.c (hunk 1 above)
Comment (antoinealb) [reply platform/uwb-beacon/platform.c:78]: By trial and error until I found a period that looked good on the board :sweat: no hard science here.

File: platform/mcu/stm32f4/flash_writer.c (hunk 2 above)
Comment (antoinealb) [reply platform/mcu/stm32f4/flash_writer.c:11]: STM32F4 Reference Manual (another important document, separate from datasheet):

Screenshot from 2019-08-16 13-58-56

It shows that the F4s with the most flash have sectors 0 to 23 -> 24 sectors.

**Comment by antoinealb** [comment]
I will add comments clarifying your points in the appropriate commits, then merge.
